name: Generate XML Feed

on:
  workflow_dispatch:

  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
          EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
        run: |
          python generate_xml.py

      - name: Commit XML
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add feed.xml
          git commit -m "Update XML feed" || echo "No changes"

          git push
